FROM node:alpine AS base

FROM base AS builder

WORKDIR /app

COPY /frontend/package*.json ./

RUN npm ci

COPY /frontend .

RUN npm run build

FROM base AS deplyer

WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3002

CMD ["node", "server.js"]