name: Build And Deply Backend

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Create .env file
              run: |
                  touch backend/.env
                  echo "${{ secrets.ENV_BACKEND }}" >> backend/.env
                  touch frontend/.env
                  echo "${{ secrets.ENV_FRONTEND }}" >> frontend/.env
            - name: Build Backend
              run: |
                   docker build -t mdpahlovi/insightbase-backend --file Dockerfile.backend .
                   docker build -t mdpahlovi/insightbase-frontend --file Dockerfile.frontend .
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push Backend to Docker
              run: |
                  docker push mdpahlovi/insightbase-backend
                  docker push mdpahlovi/insightbase-frontend
