name: Build And Deply Backend

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Create .env file
              run: |
                  touch backend/.env
                  echo "${{ secrets.ENV_BACKEND }}" >> backend/.env
                  touch frontend/.env
                  echo "${{ secrets.ENV_FRONTEND }}" >> frontend/.env
            - name: Build Image
              run: |
                  docker build -t mdpahlovi/insightbase-backend --file Dockerfile.backend .
                  docker build -t mdpahlovi/insightbase-frontend --file Dockerfile.frontend .
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push Image
              run: |
                  docker push mdpahlovi/insightbase-backend
                  docker push mdpahlovi/insightbase-frontend
            - name: Pull and Run Image
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      cd insightbase
                      docker pull mdpahlovi/insightbase-backend:latest
                      docker pull mdpahlovi/insightbase-frontend:latest
                      docker compose up -d
                      echo "Deployed Successfully"
